server {
    listen 80;
    server_name localhost;

    # Sirve archivos estáticos desde /usr/share/nginx/html
    root /usr/share/nginx/html;
    index index.html;

    # Proxy inverso — redirige /api/* a la API Flask
    location /api/ {
        proxy_pass http://api:5000/;
        # http://api:5000/ — "api" es el nombre del servicio en docker-compose
        # Docker resuelve ese nombre al IP del contenedor automáticamente
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Página estática
    location / {
        try_files $uri $uri/ /index.html;
    }
}
